image: python:3.6

stages:
  - deploy

.aws-docker: &aws-docker
  image: ridibooks/gitlab-ci-docker-aws:1.5.0

.build-template: &build
  <<: *aws-docker
  stage: deploy
  only:
    - master
  when: manual
  before_script:
    - apk add --update nodejs yarn
    - export TAG=${CI_COMMIT_SHA::8}
  script:
    - sh docs/script/export.sh
    - sh docs/script/upload.sh

.mr-build-template: &mr-build
  <<: *build
  when: manual
  only:
  except:
    - master

build-development:
  <<: *build
  variables:
    ENVIRONMENT: 'development'
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
    S3_PATH: $DEV_S3_PATH
    INDEX_S3_PATH: $DEV_INDEX_S3_PATH

build-staging:
  <<: *build
  variables:
    ENVIRONMENT: 'staging'
    AWS_ACCESS_KEY_ID: $STAGING_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $STAGING_AWS_SECRET_ACCESS_KEY
    S3_PATH: $STAGING_S3_PATH
    INDEX_S3_PATH: $STAGING_INDEX_S3_PATH

build-production:
  <<: *build
  variables:
    ENVIRONMENT: 'production'
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
    S3_PATH: $PROD_S3_PATH
    INDEX_S3_PATH: $PROD_INDEX_S3_PATH

manual-build-development:
  <<: *mr-build
  variables:
    ENVIRONMENT: 'development'
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
    S3_PATH: $DEV_S3_PATH
    INDEX_S3_PATH: $DEV_INDEX_S3_PATH

manual-build-staging:
  <<: *mr-build
  variables:
    ENVIRONMENT: 'staging'
    AWS_ACCESS_KEY_ID: $STAGING_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $STAGING_AWS_SECRET_ACCESS_KEY
    S3_PATH: $STAGING_S3_PATH
    INDEX_S3_PATH: $STAGING_INDEX_S3_PATH
