image: python:3.6

stages:
  - build
  - deploy

.aws-docker: &aws-docker
  image: ridibooks/gitlab-ci-docker-aws:latest

build:
  <<: *aws-docker
  stage: build
  only:
    - master
  before_script:
    - apk add nodejs yarn python3 make python3-dev gcc
    - pip3 install --upgrade pip
    - pip install pipenv boto3
    - make python-package-install
    - export TAG=${CI_COMMIT_SHA::8}

  script:
    - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
    - export S3_PATH=$DEV_S3_PATH
    - make ci-settings ns=development
    - sh docs/script/export.sh
    - sh docs/script/upload.sh
    - ENVIRONMENT=development docker-compose -f ./docs/docker/compose/build.yml build

    - AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY S3_PATH=$PROD_S3_PATH
    - make ci-settings ns=production
    - sh docs/script/export.sh
    - sh docs/script/upload.sh
    - ENVIRONMENT=production docker-compose -f ./docs/docker/compose/build.yml build

    - AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY S3_PATH=$PROD_S3_PATH
    - make ci-settings ns=staging
    - sh docs/script/export.sh
    - sh docs/script/upload.sh
    - ENVIRONMENT=staging docker-compose -f ./docs/docker/compose/build.yml build

.deployment-template: &deployment
  <<: *aws-docker
  stage: deploy
  when: manual
  only:
    - master
  script:
    - export TAG=${CI_COMMIT_SHA::8}
    - '`aws ecr get-login --no-include-email --region=$AWS_DEFAULT_REGION`'
    - sh docs/script/push.sh
    - sh docs/script/deploy.sh

development:
  <<: *deployment
  variables:
    ENVIRONMENT: 'development'
    ECR_REPO_URL: $DEV_LIBRARY_ECR
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY

staging:
  <<: *aws-docker
  stage: deploy
  when: manual
  only:
    - master
  variables:
    ENVIRONMENT: 'staging'
    ECR_REPO_URL: $PROD_LIBRARY_ECR
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
    RIDI_TOKEN_AUTHORIZE_URL: $PROD_LOGIN_URL
    RIDI_OAUTH2_CLIENT_ID: $PROD_CLIENT_ID
    RIDI_OAUTH2_JWT_SECRET: $PROD_JWT_SECRET
  script:
    - export TAG=${CI_COMMIT_SHA::8}
    - '`aws ecr get-login --no-include-email --region=$AWS_DEFAULT_REGION`'
    - sh docs/script/push.sh
    - sh docs/script/staging_deploy.sh

production:
  <<: *deployment
  variables:
    ENVIRONMENT: 'production'
    ECR_REPO_URL: $PROD_LIBRARY_ECR
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
    RIDI_TOKEN_AUTHORIZE_URL: $PROD_LOGIN_URL
    RIDI_OAUTH2_CLIENT_ID: $PROD_CLIENT_ID
    RIDI_OAUTH2_JWT_SECRET: $PROD_JWT_SECRET
