image: python:3.6

stages:
  - build
  - deploy

.aws-docker: &aws-docker
  image: ridibooks/gitlab-ci-docker-aws:latest

build:
  <<: *aws-docker
  stage: build
  script:
    - export TAG=${CI_COMMIT_SHA::8}
    - ENVIRONMENT=development docker-compose -f ./docker/compose/build.yml build


.deployment-template: &deployment
  <<: *aws-docker
  stage: deploy
  when: manual
  only:
    - master
  script:
    - apk add nodejs yarn
    - export TAG=${CI_COMMIT_SHA::8}
    - "`aws ecr get-login --no-include-email --region=$AWS_DEFAULT_REGION`"
    - sh scripts/push.sh
    - yarn install
    - yarn build
    - yarn export
    - aws s3 sync ./out library-static.dev.ridi.io
    - sh scripts/deploy.sh
  

development:
  <<: *deployment
  variables:
    ENVIRONMENT: "development"
    ECR_REPO_URL: $DEV_LIBRARY_ECR
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
