version: '3.4'

services:
  library-web-nginx:
    image: nginx:stable
    container_name: library-web-nginx
    restart: always
    volumes:
      - ./docs/dev/nginx/static.conf:/etc/nginx/conf.d/static.conf:ro
      - ./docs/dev/cert:/etc/nginx/cert/:ro
      - ./out/:/htdocs/www/out:ro
    ports:
      - 443:443
