version: '3.4'

services:
  library-web:
    image: node:10
    container_name: library-web
    volumes:
      - .:/htdocs/www
    working_dir: /htdocs/www
    command: ['make', 'docker-all']

  library-web-nginx:
    image: nginx:stable
    container_name: library-web-nginx
    restart: always
    volumes:
      - ./docs/dev/nginx/dynamic.conf:/etc/nginx/conf.d/dynamic.conf:ro
      - ./docs/dev/cert:/etc/nginx/cert/:ro
    ports:
      - 443:443
    depends_on:
      - library-web
    links:
      - library-web
