version: '2'

services:
  www:
    build:
      context: ../../../
      dockerfile: ./docs/docker/www/Dockerfile
    image: ${ENVIRONMENT}/library_web/www:${TAG}
  nginx:
    build:
      context: ../../../
      dockerfile: ./docs/docker/nginx/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    image: ${ENVIRONMENT}/library_web/nginx:${TAG}