version: '2'

services:
  www:
    extends:
      file: common.yml
      service: www
    environment:
      - LOGIN_URL=${LOGIN_URL}
      - JWT_SECRET=${JWT_SECRET}
    mem_limit: 512m
    mem_reservation: 256m
    logging:
      driver: awslogs
      options:
        awslogs-group: /library_web/ecs/www/node
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: node
  nginx:
    extends:
      file: common.yml
      service: nginx
    mem_limit: 512m
    mem_reservation: 64m
    restart: always
    ports:
      - 80
    links:
      - www
    logging:
      driver: awslogs
      options:
        awslogs-group: /library_web/ecs/www/nginx
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: nginx
